name: sori
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+2

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  http: ^0.13.3
  flutter_spinkit: ^5.1.0
  animated_text_kit: ^4.2.1
  firebase_core: ^1.19.2
  firebase_auth: ^3.4.2
  cloud_firestore: ^3.3.0
  modal_progress_hud_nsn: ^0.2.1
  url_launcher: ^6.1.5
  whatsapp_unilink: ^2.0.1+1
  http_auth: ^1.0.1
  flutter_email_sender: ^5.1.0
  string_validator: ^0.3.0
  flutter_paypal: ^0.0.8






dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/